# Generated by Django 6.1 on 2026-09-08 15:31

import django.db.models.deletion
from django.conf import settings
import ambit.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambit', '0002_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.UUIDField(default=ambit.base.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='ambit.role')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='ambit.scope')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'role', 'scope'), name='unique_user_role_scope')],
            },
        ),
    ]
