# Generated by Django 6.1 on 2026-09-09 11:11

import django.db.models.deletion
import ambit.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambit', '0003_roleassignment'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopeConstraint',
            fields=[
                ('id', models.UUIDField(default=ambit.base.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dimension', models.CharField(max_length=50)),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='ambit.scope')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scope', 'dimension', 'content_type', 'object_id'), name='unique_scope_constraint')],
            },
        ),
    ]
