# Generated by Django 6.1 on 2026-09-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambit', '0004_scopeconstraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='is_global',
            field=models.BooleanField(default=False, help_text='Applies to all records regardless of scope constraints.'),
        ),
    ]
