# Generated by Django 6.1 on 2026-09-10 16:03

import ambit.dimensions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambit', '0005_scope_is_global'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopeconstraint',
            name='dimension',
            field=models.CharField(choices=ambit.dimensions.scope_dimension_choices, max_length=50),
        ),
    ]
