# Generated by Django 6.1 on 2026-09-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambit', '0006_alter_scopeconstraint_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_position',
            field=models.BooleanField(default=False, help_text='Show holders of this role as a position on the pages it applies to (“Class Teacher · Omar Adel” on Grade 2 · A).'),
        ),
    ]
