# Generated by Django 6.1 on 2026-09-13 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambit', '0007_role_is_position'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scopeconstraint',
            name='unique_scope_constraint',
        ),
        migrations.AlterField(
            model_name='scopeconstraint',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='scopeconstraint',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='scopeconstraint',
            constraint=models.UniqueConstraint(fields=('scope', 'dimension', 'content_type', 'object_id'), name='unique_scope_constraint', nulls_distinct=False),
        ),
    ]
